apiVersion: v1
kind: Service
metadata:
  name: omnimind
  namespace: omnimind
  labels:
    app: omnimind
spec:
  selector:
    app: omnimind
  ports:
    - port: 8000
      targetPort: http
      name: http
  type: ClusterIP
